services:
  laravel-testing:
    build:
      context: ./docker/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        DEPLOYMENT_DIR: '/var/www/html'
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-81}:81'
      - '${VITE_PORT:-5174}:${VITE_PORT:-5174}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: off
      XDEBUG_CONFIG: client_host=host.docker.internal
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - ./:/var/www/html
    tmpfs:
      - /var/www/html/storage/framework/views
      - /var/www/html/storage/framework/cache
      - /var/www/html/storage/framework/sessions
      - /var/www/html/storage/framework/logs
    networks:
      - sail
    depends_on:
      - mysql-testing
    dns_opt:
      - use-vc # use tCP-IP DNS Resolution to fix timeouts

  mysql-testing:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
      - ./docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge
