/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "profile.show": [],
    "other-browser-sessions.destroy": [],
    "current-user-photo.destroy": [],
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "set.password.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        },
        {
            "name": "hashedEmail",
            "required": true
        }
    ],
    "set.password.update": [],
    "shifts": [
        {
            "name": "shiftDate",
            "required": true
        }
    ],
    "outstanding-reports": [],
    "reserve.shift": [],
    "save.report": [],
    "get.report-tags": [],
    "set.viewed-availability": [],
    "user.availability": [],
    "update.user.availability": [],
    "update.user.vacations": [],
    "user.location-choices": [],
    "update.user.location-choices": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
