name: Main Runner

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml

  debug-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Is tag? ${{ startsWith(github.ref, 'refs/tags/v') }}"
          echo "Will create release? ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}"

  create-release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    needs: run-tests
    uses: ./.github/workflows/create-release.yml
