name: Laravel Test

on: [push, pull_request, workflow_dispatch]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'

      - name: Create testing database
        run: mysql -uroot -h127.0.0.1 -e 'SELECT version(); CREATE DATABASE IF NOT EXISTS testing;'

      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate application key
        run: php artisan key:generate

      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          check-latest: true
#
#      - name: Install NPM dependencies
#        run: npm install
#
#      - name: Compile front-end assets
#        run: npm run build

      - name: Run PHPUnit tests
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing
        run: vendor/bin/phpunit
