name: Laravel Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/actions-setup-mysql
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
      - run: mysql -uroot -h127.0.0.1 -e 'SELECT version(); CREATE DATABASE IF NOT EXISTS testing;'
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          check-latest: true
      - name: Install NPM dependencies
        run: npm install
      - name: Compile front-end assets
        run: npm run build
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing
        run: vendor/bin/phpunit
